version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio_extractor
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKERIZED=true
    env_file:
      - .env
    command: python /main.py
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
