version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio_extractor
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKERIZED=true
      - MODE=PRODUCTION
      - WISPER_MODEL_FOLDER= /data/wisper_model
    env_file:
      - .env
    command: python ./main_bot.py
    networks:
      - mynetwork
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - data:/data
      - ./app:/app

networks:
  mynetwork:
    driver: bridge

volumes:
  data:
