version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio_extractor
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKERIZED=true
      - MODE=PRODUCTION
    env_file:
      - .env
    command: python ./main_bot.py
    networks:
      - mynetwork
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  mynetwork:
    driver: bridge
